FROM amazoncorretto:24-alpine-jdk
MAINTAINER https://github.com/bkalbitz
COPY target/bandcamp-item-detail-0.0.1-SNAPSHOT.jar bandcamp-item-detail-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/bandcamp-item-detail-0.0.1-SNAPSHOT.jar"]