services:
    bandcamp-collection-explorer-db:
        container_name: bandcamp-collection-explorer-db
        image: 'mysql:latest'
        restart: always
        ports:
          - 3306:3306
        networks:
          - bandcamp-explorer
        environment:
          MYSQL_PASSWORD_FILE: /run/secrets/collectiondb_password
          MYSQL_DATABASE: collectiondb
          MYSQL_ROOT_PASSWORD: /run/secrets/collectiondb_root_password
          MYSQL_USER: myuser
        healthcheck:
            test: mysql --user=root --password=$$(cat $$MYSQL_ROOT_PASSWORD) -e 'show databases'
            interval: 3s
            retries: 20
            timeout: 5s
        secrets:
            - collectiondb_password
            - collectiondb_root_password
    bandcamp-item-detail-db:
        container_name: bandcamp-item-detail-db
        image: 'mysql:latest'
        restart: always
        ports:
          - 3307:3306
        networks:
          - bandcamp-explorer
        environment:
          MYSQL_PASSWORD_FILE: /run/secrets/detaildb_password
          MYSQL_DATABASE: detaildb
          MYSQL_ROOT_PASSWORD: /run/secrets/detaildb_root_password
          MYSQL_USER: myuser
        healthcheck:
            test: mysql --user=root --password=$$(cat $$MYSQL_ROOT_PASSWORD) -e 'show databases'
            interval: 3s
            retries: 20
            timeout: 5s
        secrets:
            - detaildb_password
            - detaildb_root_password
    bandcamp-collection-explorer:
        container_name: bandcamp-collection-explorer
        build:
            context: bandcamp-collection-explorer
            dockerfile: Dockerfile
        image: bandcamp-collection-explorer
        ports:
            - 8080:8080
        depends_on:
            bandcamp-collection-explorer-db:
                condition: service_healthy
        networks:
            - bandcamp-explorer
        secrets:
            - collectiondb_password
    bandcamp-item-detail:
        container_name: bandcamp-item-detail
        build:
            context: bandcamp-item-detail
            dockerfile: Dockerfile
        image: bandcamp-item-detail
        ports:
            - 8081:8081
        depends_on:
            bandcamp-item-detail-db:
                condition: service_healthy
        networks:
            - bandcamp-explorer
        secrets:
            - detaildb_password
    bandcamp-collection-intersection:
        container_name: bandcamp-collection-intersection
        build:
            context: bandcamp-collection-intersection
            dockerfile: Dockerfile
        image: bandcamp-collection-intersection
        ports:
            - 8082:8082
        networks:
            - bandcamp-explorer
    bandcamp-collection-client:
        container_name: bandcamp-explorer-client
        build:
            context: bandcamp-explorer-client
            dockerfile: Dockerfile
        image: bandcamp-explorer-client
        ports:
            - 4200:4200
        networks:
            - bandcamp-explorer
networks:
    bandcamp-explorer:
        driver: bridge
secrets:
  collectiondb_password:
    file: ./collectiondb_password.txt
  collectiondb_root_password:
    file: ./collectiondb_root_password.txt
  detaildb_password:
    file: ./detaildb_password.txt
  detaildb_root_password:
    file: ./detaildb_root_password.txt