FROM amazoncorretto:24-alpine-jdk
MAINTAINER https://github.com/bkalbitz
COPY target/bandcamp-collection-intersection-0.0.1-SNAPSHOT.jar bandcamp-collection-intersection-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/bandcamp-collection-intersection-0.0.1-SNAPSHOT.jar"]